sudo: required
services: 
  - docker

before_install:
  - docker build -t marley/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run marley/react-test npm test -- --coverage

after_success:
  - docker build -t marley/multi-client ./client
  - docker build -t marley/multi-nginx ./nginx
  - docker build -t marley/multi-server ./server
  - docker build -t marley/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push marley/multi-client
  - docker push marley/multi-nginx 
  - docker push marley/multi-server
  - docker push marley/multi-worker
